### ISSUE TITLE
Error when pip install in MacOS

### ISSUE THREAD

**Issue by jacksenteh** [lukas/ml-class#56]
I ran into installation error when I execute 'pip install wandb'.

![2020-04-02 at 11 46 AM](https://user-images.githubusercontent.com/17850123/78208687-8ec09d80-74d7-11ea-9363-f001aabc7d75.png)
![2020-04-02 at 11 46 AM](https://user-images.githubusercontent.com/17850123/78208714-a009aa00-74d7-11ea-9812-e9b0932b1203.png)

OS: MacOS Catalina v10.15.3
Device: Macbook pro 2017

Does anyone got the same problem?

**Comment by charlesfrye** [comment]
This looks like an error in the build of one of our dependencies, [watchdog](https://github.com/gorakhargosh/watchdog), rather than in wandb itself.

It looks to be a compilation issue, and may be due to an improper installation of Python. On OS X, you need [to install XCode](https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-macos).

Good luck!
